sudo: required
services:
- docker
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
  - secure: "E9XPAN4lodVShoJ/cxcHS87pHgk8zu4vMWlamN77sfGXIQx8bvSggO1463m8g+BS+lDULiTUNENCZxS603SIjtNV2jzDJoW0Led/8ZFT/+Wa/CJMFdd0jT/pnYGVmTeuiPwdjqwTx2KW7L+e4l1IpnYaGYjljgJGNTDCLSe4hU5B4eKIc2qgpvIWM7pxTo/nBBFoS0ARyNlk9z/BTt6JV9s7lmKe9tXqJzw6u7tifklhKP/p2goZICZLHWIC3/95igOM3Op2TQceyqiDjYjYFxw5U3iDkIBmUFnUXxGVMQODIIY17VUKVei3oHuiIp3jB60+zfXHHBXCdNCoc1yqIvlkNjnqMSGSXq+bKM1qqmf7DgGtTgNTFfNcpatulSNMm9XMW792zcqEadMHMFbepQFL1NC8Si3N2Vy1morSZTKow/XqCwJBijZoDLnYDvDpB9yoadYVBMib2qkteANKWYMoZD8Iydnv3qZ9cTxO2KF3ywQiBtZA1Rg4SELIZub+0zTnP2DSyrSka4P4QrYHJ1y+W3r5w9WASNaQUQxBlwSx21gGjxAOKoCQvs/joPPy6U3gVBA3HUgh0YF6S6EcyhAzFNwY7cE62YrlxE40RdD6tP6ZMCc2nUeTypo5mSIJE/1PIS45TcXW3rHwNSMbled4vpW29Rmk5XrsgK10QwQ="
  - secure: "faXKYN515K7iRGhzti64GrnZ/OmvcvHP8mm7Cz0uy9lr8/Bo//FNF3HLYiZi0yCn6PsBjkW1cmdGlEgn4bdTB3U28yNx2O6ktRUAaMpHyFQH3/BsecB10i1X874iSYovk5Y7PaH/6UDfuSwek0UObeZuqCOT0/1isUuDs2YGoyFhQpCKMfm8DOji8CyKWW+n9Uq5zmf7c9QdrvtiJctdoYnqMixKlXmHZOBF9rZ2wNa9XD5jVDb+hOCBwoOO5u0jr8kObbCtSbacC22+8qDw6BSg/IZgrnq7K1sRH0f0lN1bXKsFXQRaUdfmRqsToNlHTaH6+mBk8Y5lB29FdajW7NEsTbM1uTcNUHgmmomflKe+QMQXXz1DvqOUPjdSLHua+daYCyCbdBcdb+R25MvCKZq4x1+ZSUccpGqhuMmqZGJQ5PrH7zrxQ/jVRBBZMQmA+K04ZR5BWYOEAvZNE9eLulwcSxQYtYy9vvBK7RohuViFdexxGztsYKj+4kbtUP9uncH+EBhhsWQRD02VSRpEgg2YzI8KBzwRfxlE6ybNw4XBeSPC2MwotDIC+2wirzCNrHIncvuZPcnuBJs5GEOFomr2w/GgXGOlH55ew7WU9EZREd3JeuKD0V8y/73Xdts55U09DYCEq5lHyh+pRzoLpntvdS6lNMbVIGba1bQEoug="
jobs:
  include:
  - stage: Unit tests
    script:
    - "./gradlew test --stacktrace --info"
  - stage: Integration tests
    script:
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start kafka cassandra redis"
    - sleep 1m
    - "./gradlew integrationTest --stacktrace --info"
  - stage: Staging
    if: tag IS blank
    name: Build Broker
    script:
    - gradle shadowJar
    - mv $TRAVIS_BUILD_DIR/.codedeploy/.appspec.yml $TRAVIS_BUILD_DIR/build/libs/appspec.yml
    - mv $TRAVIS_BUILD_DIR/.codedeploy $TRAVIS_BUILD_DIR/build/libs/
    - tar -czvf $TRAVIS_BUILD_DIR/build/libs/broker.tar -C $TRAVIS_BUILD_DIR/build/libs/ cloud-broker-1.0-SNAPSHOT-all.jar appspec.yml .codedeploy
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: "py8GUiWXB+h6wUD/DyelekT5LZmExbl+FgRlZAlFvgWitUMu5fkkBKRL+1kBNPTytxTLWke14585gOKr8quHHZyM97ykVkQg7DXJC+TS51nLp4+0piG+NPBBmoodDm1EXJ+Hv6U78eZcOw3gPsw8WhisZFGOknVZMN0aHXsJm3qUMHGBMgttd+LKz+sk82CdzpW90iPwlehaPZD/Fu1ciWXjmcBagBuMrLDJMoLSKNEHMhqwQzGAtAbij9PBucIdAknEKsuAU9bOiOWHxXlH+tINhYuuF8O5zCUovjVYDvxjp/tqWbiiEGrL9sI+PdxGP+OwOPynb+fWkESCrj6OPx2aIMLdeeiozq/aiUKlasE8trRqv5Ohm8+dVwSwCzwc6YMGMpngHBTRPpS+iuhAEKc8ivYIp2Vno8iKvbFWhCgz6lzjgYEefjnsGwOlxiM0pt8IeqIjXEu4UadulgrcUHox6F7Hi6NjfFAEC2c8y89ZXzirpZ7TGXzBhJsFHM9jETTF390sGekb+6ZLH2/Uto8JjpfORQAiaV4vQ1vomKTgTEgyQ8cwbmW8b/3KvXtZYArlnsAvcwBfKrBfdP5U2EwfcZ8FgI7mTAG93pGQQfgGS0Ehbsyx+mqCzOSbHA+EO7xACzOoVJzN1VNfLVzK1GjVm47inEf05PL/rk8ucpE="
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: broker/releases
      local-dir: "$TRAVIS_BUILD_DIR/build/libs/"
      acl: private
      region: eu-west-1
      skip_cleanup: true
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: "py8GUiWXB+h6wUD/DyelekT5LZmExbl+FgRlZAlFvgWitUMu5fkkBKRL+1kBNPTytxTLWke14585gOKr8quHHZyM97ykVkQg7DXJC+TS51nLp4+0piG+NPBBmoodDm1EXJ+Hv6U78eZcOw3gPsw8WhisZFGOknVZMN0aHXsJm3qUMHGBMgttd+LKz+sk82CdzpW90iPwlehaPZD/Fu1ciWXjmcBagBuMrLDJMoLSKNEHMhqwQzGAtAbij9PBucIdAknEKsuAU9bOiOWHxXlH+tINhYuuF8O5zCUovjVYDvxjp/tqWbiiEGrL9sI+PdxGP+OwOPynb+fWkESCrj6OPx2aIMLdeeiozq/aiUKlasE8trRqv5Ohm8+dVwSwCzwc6YMGMpngHBTRPpS+iuhAEKc8ivYIp2Vno8iKvbFWhCgz6lzjgYEefjnsGwOlxiM0pt8IeqIjXEu4UadulgrcUHox6F7Hi6NjfFAEC2c8y89ZXzirpZ7TGXzBhJsFHM9jETTF390sGekb+6ZLH2/Uto8JjpfORQAiaV4vQ1vomKTgTEgyQ8cwbmW8b/3KvXtZYArlnsAvcwBfKrBfdP5U2EwfcZ8FgI7mTAG93pGQQfgGS0Ehbsyx+mqCzOSbHA+EO7xACzOoVJzN1VNfLVzK1GjVm47inEf05PL/rk8ucpE="
      bucket: eu-west-1-stg-streamr-vault
      key: broker/releases/broker.tar
      application: eu-west-1-stg-broker-codedeploy
      deployment_group: eu-west-1-stg-broker-deployment-group
      region: eu-west-1
  - stage: Build docker (dev)
    if: tag IS blank
    env:
    - OWNER=streamr
    - IMAGE_NAME=cloud-broker
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
  - stage: Build docker (stg)
    if: tag IS blank
    env:
    - OWNER=streamr
    - IMAGE_NAME=cloud-broker
    - TAG=stg
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
